:bug: Added try and catch to instantiate sweetalert2 in diferents versions
pagarme/woocommerce pull request #103
Opened 2022-04-20 05:32 UTC by danielmadu

| Questions     | Answers
| ------------- | -------------------------------------------------------
| **What?**      | Fix Sweetalert2 object instantiate 
| **How?**       | Adding try catch to verify how it does

2022-04-20 12:50 UTC, dias-joao requested changes
@danielmadu, idealmente não deve-se repetir blocos de código para auxiliar na manutenibilidade do código fonte. Assim sendo, ao invés de duplicar o código, teste se a função swal está definida:
Exemplo:

`
let message = {
                    type: 'error',
                    text: 'O valor não pode ser maior que total do pedido!'
                };
                
                try{
                swal(message)
                }catch (e){
                new swal(message)
                }
`
Ou.. para mais performance, troque o try/catch por um simples if verificando se a swal é uma função:

`if (typeof swal !== 'function') {new swal(message)}`

2022-04-20 20:23 UTC, dias-joao approved these changes

2022-04-20 20:33 UTC, netorodrigues approved these changes

2022-04-25 20:53 UTC, dias-joao approved these changes

2022-04-26 12:11 UTC, netorodrigues approved these changes

2022-04-26 13:22 UTC, merged