Feature/paop 492
pagarme/woocommerce pull request #105
Opened 2022-05-10 04:02 UTC by acedraz

| Questions     | Answers
| ------------- | -------------------------------------------------------
| **What?**         | Notify that the integration environment is sandbox
| **Why?**          | Alert that it is necessary to change if ecommerce is in production mode
| **How?**          | Validate keys and hub environment and alert in admin area and checkout payment methods

2022-05-10 10:58 UTC, dias-joao requested changes

2022-05-10 10:58 UTC, dias-joao commented on assets/stylesheets/admin/style.css
> +.message.warning {
Ailsan, nós sempre adicionamos o pre-fixo pagar-me nas classes de CSS para evitar conflitos com temas e o padrão do Wordpress. O nome sugerido para sua classe é bastante genérico, logo, uma sugestão:

```suggestion
.pagar-me-message-warning {
```

2022-05-10 12:38 UTC, acedraz commented on assets/stylesheets/admin/style.css
> +.message.warning {
@dias-joao alterei o nome do css para pagar-me-message-warning e aproveitei para modificar a nomenclatura do método que checa se é modo sandbox para o padrão woocommerce. Commit e41a9cb

2022-05-10 12:59 UTC, danielmadu approved these changes

2022-05-13 03:00 UTC, dias-joao approved these changes

2022-05-13 03:01 UTC, merged