Enhancement/paop 487 display payment data in woocommerce api
pagarme/woocommerce pull request #106
Opened 2022-05-12 16:31 UTC by danielmadu

| Questions     | Answers
| ------------- | -------------------------------------------------------
| **What?**         | Change payment method and payment method title from order
| **Why?**          | Display correct payment method to generate reports

2022-05-12 22:48 UTC, mauriciohaygert approved these changes

2022-05-13 02:54 UTC, dias-joao requested changes

2022-05-13 02:54 UTC, dias-joao commented on src/Controller/Checkout.php
> +            $order->transaction_id     = $response->getPagarmeId()->getValue();
Daniel, notei uma situação que pode causar eventuais falhas aqui:
> Se `$wc_order` for uma instância vazia de `WC_Order`, a instância `$order` terá todas as propriedades nulas/defaults e por conseguinte, todos os métodos invocados dentro deste IF poderão quebrar/gerar exceptions.  Para contornar isso, talvez a sugestão seja testar se `$wc_order->get_order_number()` retorna algum inteiro e não vazio.

2022-05-13 02:54 UTC, dias-joao commented on src/Controller/Checkout.php
> +            $order->update_meta('_payment_method_title', $fields['payment_method']);
Esse campo `$fields['payment_method']` traz o título da forma de pagamento já estilizado? Ex: `Cartão de crédito`? Ou algo do tipo `2_cards`?

2022-05-13 02:54 UTC, dias-joao commented on src/Controller/Gateways.php
> +    public function process_payment($order_id): array
Sei que está fora do contexto dessa implementação: neste método não existe nenhuma hipótese de haver insucesso?
Linha 151.

2022-05-17 18:28 UTC, mauriciohaygert approved these changes

2022-05-17 19:05 UTC, dias-joao approved these changes

2022-05-17 19:06 UTC, merged