PAOPN-257: fix pt_br translations on checkout error
pagarme/woocommerce pull request #165
Opened 2022-11-23 23:50 UTC by claudio-pagarme

fix pt_br translations on checkout errors

2022-11-24 12:17 UTC, RafaMelazzo reviewed
`assets/javascripts/front/main.js`
Poderia remover a linha 796, e retornar "**error**" nas linhas 800 e 807.

`src/Core.php`
Poderia remover "_uma string_" na linha 283, como foi feito na tradução da linha 281 :)

2022-11-25 12:10 UTC, fabiano-mallmann requested changes
assets/javascripts/front/main.js: unnecessary "output" variable assignment
src/Core.php: line 281, change "numéro" to "número"

2022-11-28 11:50 UTC, fabiano-mallmann approved these changes

2022-11-28 13:36 UTC, RafaMelazzo approved these changes

2022-11-29 13:09 UTC, merged