WIP: PAOPN-399: Clear card error messages in checkout
pagarme/woocommerce pull request #238
Opened 2023-06-22 18:45 UTC by mateus-picoloto

2023-06-22 19:05 UTC, RafaMelazzo requested changes

2023-06-22 19:05 UTC, RafaMelazzo commented on languages/woo-pagarme-payments-pt_BR.po
> +msgid "Cant check card form: Invalid element received."
Can't

2023-06-22 19:05 UTC, RafaMelazzo commented on languages/woo-pagarme-payments-pt_BR.po
> +msgstr "Timeout na tokenização."
Sugestão: O tempo limite de tokenização expirou.

2023-06-22 19:05 UTC, RafaMelazzo commented on src/Core.php
> +                __('Cant check card form: Invalid element received.', 'woo-pagarme-payments'),
Can't

2023-06-22 19:05 UTC, RafaMelazzo commented on src/Core.php
> +            'card: Cant check card form: Invalid element received'        =>
Can't

2023-06-22 19:15 UTC, mateus-picoloto commented on languages/woo-pagarme-payments-pt_BR.po
> +msgid "Cant check card form: Invalid element received."
Done

2023-06-22 19:15 UTC, mateus-picoloto commented on languages/woo-pagarme-payments-pt_BR.po
> +msgstr "Timeout na tokenização."
Done

2023-06-22 19:15 UTC, mateus-picoloto commented on src/Core.php
> +                __('Cant check card form: Invalid element received.', 'woo-pagarme-payments'),
Done

2023-06-22 19:15 UTC, mateus-picoloto commented on src/Core.php
> +            'card: Cant check card form: Invalid element received'        =>
Done

2023-06-23 12:18 UTC, mauriciohaygert approved these changes

2023-06-23 12:44 UTC, merged