feat: create process free trial subscription
pagarme/woocommerce pull request #270
Opened 2023-08-02 23:52 UTC by mauriciohaygert

create process free trial subscription

2023-08-03 16:21 UTC, mateus-picoloto requested changes

2023-08-04 15:27 UTC, mateus-picoloto submitted a review, later dismissed

2023-08-04 19:54 UTC, RafaMelazzo commented on src/Model/Subscription.php
> +                'Ocorreu um problema ao criar o teste grátis da assinatura. Tente novamente mais tarde!',
Essa mensagem deveria estar em inglês e adicionar tradução?

2023-08-04 21:01 UTC, RafaMelazzo requested changes

2023-08-04 21:01 UTC, RafaMelazzo commented on src/Model/Subscription.php
> +                'There was a problem with the payment exchange.',
Faltou `__()`

2023-08-04 21:01 UTC, RafaMelazzo commented on src/Model/Subscription.php
> +                'Error creating subscription free trial.',
Faltou `__()`

2023-08-07 12:44 UTC, fabiano-mallmann approved these changes

2023-08-07 14:09 UTC, RafaMelazzo submitted a review, later dismissed

2023-08-07 14:11 UTC, RafaMelazzo approved these changes

2023-08-07 14:11 UTC, mateus-picoloto approved these changes

2023-08-07 14:12 UTC, merged