feat: add pagar.me dash validation
pagarme/woocommerce pull request #296
Opened 2023-09-13 12:32 UTC by RafaMelazzo

2023-09-13 17:16 UTC, mateus-picoloto requested changes

2023-09-13 17:16 UTC, mateus-picoloto commented on src/Controller/HubAccounts.php
> +            $this->notices[] = __($noticesList[$error], 'woo-pagarme-payments');
Alguns items do array que está sendo chamado para traduzir são um array também, não sendo possível traduzir eles

2023-09-13 17:39 UTC, mateus-picoloto requested changes

2023-09-13 17:39 UTC, mateus-picoloto commented on src/Model/Config.php
> +    public function getDashUrl(): mixed {
Remover o retorno do tipo mixed que não é compatível com versão antiga do php

2023-09-13 18:11 UTC, mateus-picoloto approved these changes

2023-09-13 18:39 UTC, mateus-picoloto approved these changes

2023-09-13 18:44 UTC, fabiano-mallmann commented on src/Controller/HubAccounts.php
> +    private function onPagarmePage()
Poderia iniciar com o false's primeiro e depois os true's

2023-09-13 18:52 UTC, fabiano-mallmann commented on vendor/pagarme/ecommerce-module-core/src/Kernel/Aggregates/Configuration.php
> +            "merchantId" => $this->merchantId,
Utilizar o $this->getMerchantId()

2023-09-13 18:53 UTC, fabiano-mallmann commented on vendor/pagarme/ecommerce-module-core/src/Kernel/Aggregates/Configuration.php
> +    public function setAccountId($setAccountId)
nome do argumento fora dos padrões

2023-09-13 18:53 UTC, fabiano-mallmann commented on vendor/pagarme/ecommerce-module-core/src/Kernel/Aggregates/Configuration.php
> +    public function setMerchantId($setMerchantId)
nome do argumento fora dos padrões

2023-09-13 18:55 UTC, fabiano-mallmann commented on src/Service/AccountService.php
> +    public function convertData($response)
Esse método faz sentido?

2023-09-13 20:09 UTC, fabiano-mallmann commented on src/Controller/HubAccounts.php
> +            $dashUrl = "https://dash.pagar.me/{$this->getMerchantId()}/{$this->getAccountId()}/settings/{$dashPage}/";
Notei que tem esse uso da URL (ou parte dela) em outro lugar, não compensa criar uma função para isso?

2023-09-13 21:30 UTC, mauriciohaygert commented on src/Controller/HubAccounts.php
> +    private function onPagarmePage()
Tem q ser nessa ordem mesmo. Poderia ser tudo em um IF apenas, ou direto no return. Mas dessa maneira foi a que ficou mais legível.

2023-09-14 12:20 UTC, fabiano-mallmann submitted a review, later dismissed

2023-09-14 12:22 UTC, mateus-picoloto submitted a review, later dismissed

2023-09-14 13:00 UTC, mateus-picoloto submitted a review, later dismissed

2023-09-14 13:04 UTC, fabiano-mallmann approved these changes

2023-09-14 13:04 UTC, mateus-picoloto approved these changes

2023-09-14 13:07 UTC, merged