docs: updating project docs
pagarme/woocommerce pull request #353
Opened 2023-11-24 18:59 UTC by mateus-picoloto

![Git Merge](https://media.giphy.com/media/cFkiFMDg3iFoI/giphy.gif)

> [!IMPORTANT]
> Certifique-se de criar o PR para a branch **develop**.

### Qual o tipo de PR é esse? (marque todos os aplicáveis)
- [ ] Refatoração
- [ ] Adição de funcionalidade
- [ ] Correção de bug
- [ ] Otimização
- [x] Atualização de documentação

### Descrição
Atualização das documentações do repositório.

### Cenários testados
N/A

2023-11-27 12:29 UTC, fabiano-mallmann commented on docs/README.md
> +Se você está interessado em contribuir para o desenvolvimento deste projetos, ficamos felizes em receber sua ajuda! No [contributing.md](.github/contributing.md) está o guia de como contribuir com o
"...deste projeto, ficaremos felizes em receber sua ajuda!"

2023-11-27 12:30 UTC, RafaMelazzo requested changes

2023-11-27 12:30 UTC, RafaMelazzo commented on .github/contributing.md
> +    * feat: nova funcionalidade
As mensagens devem ser em inglês, mas os exemplos estão todos em português. Acredito que pode gerar confusão...

2023-11-27 12:35 UTC, fabiano-mallmann commented on .github/contributing.md
> +    * feat: nova funcionalidade
Eu acho que não é exemplo de commit, é exemplo de Conventional Commits (feat, refactor, fix, entre outras)

2023-11-27 13:27 UTC, mateus-picoloto commented on .github/contributing.md
> +    * feat: nova funcionalidade
A ideia seria dar alguns exemplos do que é cada um dos tipos de commit, mas já que gerou confusão acham melhor já deixa em inglês mesmo @fabiano-mallmann e @RafaMelazzo?

2023-11-27 13:28 UTC, mateus-picoloto commented on docs/README.md
> +Se você está interessado em contribuir para o desenvolvimento deste projetos, ficamos felizes em receber sua ajuda! No [contributing.md](.github/contributing.md) está o guia de como contribuir com o
Ajustado

2023-11-27 13:44 UTC, fabiano-mallmann commented on .github/contributing.md
> +    * feat: nova funcionalidade
Acredito que poderia ter exemplos de commit e no exemplo de Conventional Commits utilizar outra maneira para exemplificar, utilizar (feat: nova funcionalidade) parece que é um exemplo de commit.
| Nomeclatura | Explicação |
|--------|--------|
| **feat** | Para novas funcionalidades |
| **fix** | Para correções de bugs |

2023-11-27 15:55 UTC, RafaMelazzo commented on .github/contributing.md
> +    * feat: nova funcionalidade
Boa!

2023-11-27 16:49 UTC, mateus-picoloto commented on .github/contributing.md
> +    * feat: nova funcionalidade
alterado @fabiano-mallmann e @RafaMelazzo

2023-11-27 20:35 UTC, RafaMelazzo requested changes

2023-11-27 20:36 UTC, RafaMelazzo commented on .github/contributing.md
> +    * feat: nova funcionalidade
Perfeito!

2023-11-27 20:42 UTC, mateus-picoloto commented on .github/contributing.md
> +* feat: adding exclude saved credit card to customer
ajustado

2023-11-27 20:54 UTC, RafaMelazzo approved these changes

2023-11-29 12:33 UTC, fabiano-mallmann approved these changes

2023-11-30 13:27 UTC, merged