feat: add 3ds admin configs
pagarme/woocommerce pull request #394
Opened 2024-03-05 20:19 UTC by mateus-picoloto

![Git Merge](https://media.giphy.com/media/cFkiFMDg3iFoI/giphy.gif)

> [!IMPORTANT]
> Certifique-se de criar o PR para a branch **develop**.

### Qual o tipo de PR é esse? (marque todos os aplicáveis)
- [ ] Refatoração
- [X] Adição de funcionalidade
- [ ] Correção de bug
- [ ] Otimização
- [ ] Atualização de documentação

### Descrição
Adicionado as configurações de 3ds no admin.

### Cenários testados
Salvo as configurações e validado se estavam na variável wc_pagarme_checkout no checkout.

2024-03-05 20:35 UTC, RafaMelazzo requested changes

2024-03-05 20:35 UTC, RafaMelazzo commented on languages/woo-pagarme-payments-pt_BR.po
> +msgid "3DS Enable"
Enable 3DS

2024-03-05 20:35 UTC, RafaMelazzo commented on src/Controller/Gateways/CreditCard.php
> +            'label' => __('3DS Enable', 'woo-pagarme-payments'),
Enable 3DS

2024-03-05 20:39 UTC, mateus-picoloto commented on languages/woo-pagarme-payments-pt_BR.po
> +msgid "3DS Enable"
Ajustado

2024-03-05 20:53 UTC, RafaMelazzo approved these changes

2024-03-07 14:15 UTC, fabiano-mallmann approved these changes

2024-03-07 14:22 UTC, merged