feat: add 3ds status to order admin page
pagarme/woocommerce pull request #401
Opened 2024-03-20 18:10 UTC by mateus-picoloto

![Git Merge](https://media.giphy.com/media/cFkiFMDg3iFoI/giphy.gif)

> [!IMPORTANT]
> Certifique-se de criar o PR para a branch **develop**.

### Qual o tipo de PR é esse? (marque todos os aplicáveis)
- [ ] Refatoração
- [x] Adição de funcionalidade
- [ ] Correção de bug
- [ ] Otimização
- [ ] Atualização de documentação

### Descrição
Adição do status de 3ds a página de pedido do admin.

### Cenários testados
Descreva brevemente quais foram os cenários testados com as alterações feitas neste PR.

2024-03-20 18:33 UTC, RafaMelazzo requested changes

2024-03-20 18:33 UTC, RafaMelazzo commented on src/Helper/Utils.php
> +                || (0 === strpos(self::server('QUERY_string'), 'wc-ajax')));
Desfazer essa alteração

2024-03-20 18:38 UTC, mateus-picoloto commented on src/Helper/Utils.php
> +                || (0 === strpos(self::server('QUERY_string'), 'wc-ajax')));
Ajustado

2024-03-20 18:39 UTC, RafaMelazzo approved these changes

2024-03-21 15:03 UTC, fabiano-mallmann approved these changes

2024-03-21 15:03 UTC, merged