fix: remove require fields modal
pagarme/woocommerce pull request #403
Opened 2024-03-21 20:42 UTC by mateus-picoloto

![Git Merge](https://media.giphy.com/media/cFkiFMDg3iFoI/giphy.gif)

> [!IMPORTANT]
> Certifique-se de criar o PR para a branch **develop**.

### Qual o tipo de PR é esse? (marque todos os aplicáveis)
- [ ] Refatoração
- [ ] Adição de funcionalidade
- [X] Correção de bug
- [ ] Otimização
- [ ] Atualização de documentação

### Descrição
Remoção da modal de preencher dados obrigatórios.

### Cenários testados
Tentar comprar cartão sem bandeira aparece a mensagem dados inválidos

2024-03-21 21:37 UTC, RafaMelazzo requested changes

2024-03-21 21:37 UTC, RafaMelazzo commented on languages/woo-pagarme-payments-pt_BR.po
> +"PO-Revision-Date: 2024-03-21 16:52-0300\n"
Linha foi duplicada.

2024-03-21 21:37 UTC, RafaMelazzo commented on src/Block/Checkout/Form/Card.php
> +                __('There was a problem finding the addresses.', 'woo-pagarme-payments'),
Tirar `addresses` do plural: `address`

2024-03-21 21:37 UTC, RafaMelazzo commented on src/Block/Checkout/Form/Card.php
> +                __('Invalid Data', 'woo-pagarme-payments'),
Não deveria ser `Invalid card brand`?

2024-03-21 21:37 UTC, RafaMelazzo commented on src/Block/Checkout/Form/Card.php
> +                __('Timeout na tokenização.', 'woo-pagarme-payments'),
Mensagem em português: `Tokenization timeout`

2024-03-22 12:28 UTC, mateus-picoloto commented on src/Block/Checkout/Form/Card.php
> +                __('Invalid Data', 'woo-pagarme-payments'),
Isso foi alinhado com a Chris para ser uma mensagem genérica pra não dar brecha pra fraudador.

2024-03-22 12:38 UTC, mateus-picoloto commented on languages/woo-pagarme-payments-pt_BR.po
> +"PO-Revision-Date: 2024-03-21 16:52-0300\n"
Ajustado

2024-03-22 12:38 UTC, mateus-picoloto commented on src/Block/Checkout/Form/Card.php
> +                __('There was a problem finding the addresses.', 'woo-pagarme-payments'),
Ajustado

2024-03-22 13:35 UTC, RafaMelazzo approved these changes

2024-03-22 18:42 UTC, fabiano-mallmann approved these changes

2024-03-22 18:51 UTC, merged