Add credit card to checkout blocks
pagarme/woocommerce pull request #410
Opened 2024-04-11 20:38 UTC by RafaMelazzo

![Git Merge](https://media.giphy.com/media/cFkiFMDg3iFoI/giphy.gif)

> [!IMPORTANT]
> Certifique-se de criar o PR para a branch **develop**.

### Qual o tipo de PR é esse? (marque todos os aplicáveis)
- [ ] Refatoração
- [x] Adição de funcionalidade
- [ ] Correção de bug
- [ ] Otimização
- [ ] Atualização de documentação

### Descrição
Adição do método de pagamento Cartão de Crédito ao novo checkout.

### Cenários testados
Compras com cartão de crédito no novo checkout e no antigo. Testes efetuados a vista, a prazo e com wallet.

2024-04-23 12:34 UTC, fabiano-mallmann commented on woo-pagarme-payments.php
> +// add_action(
Esse código deveria existir?

2024-04-23 12:35 UTC, fabiano-mallmann commented on webpack.config.js
> +    credit_card: './assets/javascripts/front/reactCheckout/payments/creditCard/index.js',
Indentação incorreta.

2024-04-25 12:06 UTC, mateus-picoloto requested changes

2024-04-25 12:06 UTC, mateus-picoloto commented on woo-pagarme-payments.php
> +// add_action(
Não, precisa ser removido.

2024-04-29 13:57 UTC, fabiano-mallmann commented on src/Concrete/WoocommercePlatformOrderDecorator.php
> +            $customer = $this->getRegisteredCustomer($customerId);
Não irá afetar!

2024-04-29 14:02 UTC, fabiano-mallmann commented on src/Concrete/WoocommercePlatformOrderDecorator.php
> +                $fieldIsNotSet = !array_key_exists($requiredField, $platformAddress)
Conversamos e a solução foi ignorar ele por momento e adicionar isso numa outra branch e realizar o PR para develop

2024-05-08 14:49 UTC, RafaMelazzo commented on assets/stylesheets/front/style.css
> +    background-color: rgb(0, 0, 0);
Tratar em outra branch

2024-05-08 14:50 UTC, RafaMelazzo commented on src/Block/Checkout/Form/Card.php
> +                __('Failed to generate Token for 3ds, try again.', 'woo-pagarme-payments'),
Tratar em outra branch

2024-05-08 14:51 UTC, RafaMelazzo commented on vendor/pagarme/ecommerce-module-core/src/Payment/Aggregates/Customer.php
> +         return $this->getAddress()->convertToSDKRequest();
Tratar em outra branch

2024-05-08 14:51 UTC, RafaMelazzo commented on vendor/pagarme/ecommerce-module-core/src/Payment/Aggregates/Customer.php
> +         return $this->getPhones()->convertToSDKRequest();
Tratar em outra branch

2024-05-08 15:08 UTC, mateus-picoloto commented on assets/javascripts/front/reactCheckout/payments/Card/inputs/components/InputExpiry/index.js
> +    setErrors: PropTypes.func.isRequired,
Resolvido

2024-05-08 15:08 UTC, mateus-picoloto commented on assets/javascripts/front/reactCheckout/payments/Card/inputs/components/InputHolderName/index.js
> +    setErrors: PropTypes.func.isRequired,
Resolvido

2024-05-08 15:08 UTC, mateus-picoloto commented on assets/javascripts/front/reactCheckout/payments/Card/inputs/components/InputNumber/index.js
> +    // onCheckoutValidation: PropTypes.bool.isRequired,
Resolvido

2024-05-08 15:08 UTC, mateus-picoloto commented on assets/javascripts/front/reactCheckout/payments/Card/inputs/components/MaskedInput/index.js
> +    cardIndex: PropTypes.number.isRequired,
Resolvido

2024-05-08 15:09 UTC, mateus-picoloto commented on assets/javascripts/front/reactCheckout/payments/Card/useCardValidation.js
> +        const splitDate = value.split('/');
Resolvido

2024-05-08 15:09 UTC, mateus-picoloto commented on assets/javascripts/front/reactCheckout/payments/Card/useCardValidation.js
> +        const validMonth = expiryMonth >= 1 && expiryMonth <= 12;
Resolvido

2024-05-08 15:09 UTC, mateus-picoloto commented on assets/javascripts/front/reactCheckout/payments/billet/index.js
> +import PropTypes from "prop-types";
Resolvido

2024-05-08 15:09 UTC, mateus-picoloto commented on assets/javascripts/front/reactCheckout/payments/pix/index.js
> +import PaymentWithInstructions from "../PaymentWithInstructions";
Resolvido

2024-05-08 15:09 UTC, mateus-picoloto commented on src/Block/ReactCheckout/AbstractPaymentMethodBlock.php
> +        wp_set_script_translations($scriptName, 'woo-pagarme-payments');
Resolvido

2024-05-08 15:11 UTC, mauriciohaygert approved these changes

2024-05-08 15:12 UTC, mateus-picoloto approved these changes

2024-05-10 18:12 UTC, fabiano-mallmann approved these changes

2024-05-10 20:28 UTC, merged