WIP: improve: add filters and docs to split
pagarme/woocommerce pull request #416
Opened 2024-04-25 12:27 UTC by fabiano-mallmann

![Git Merge](https://media.giphy.com/media/cFkiFMDg3iFoI/giphy.gif)

> [!IMPORTANT]
> Certifique-se de criar o PR para a branch **develop**.

### Qual o tipo de PR é esse? (marque todos os aplicáveis)
- [ ] Refatoração
- [x] Adição de funcionalidade
- [ ] Correção de bug
- [ ] Otimização
- [x] Atualização de documentação

### Descrição
Descreva brevemente as alterações feitas neste PR.

### Cenários testados
Descreva brevemente quais foram os cenários testados com as alterações feitas neste PR.

2024-05-02 17:30 UTC, mateus-picoloto submitted a review, later dismissed

2024-05-06 12:57 UTC, RafaMelazzo requested changes

2024-05-06 12:57 UTC, RafaMelazzo commented on tests/Concrete/WoocommerceCoreSetupTest.php
> +        $configMock->shouldReceive('getPublicKey')->andReturn('test');
Remover duplicado

2024-05-06 21:14 UTC, RafaMelazzo approved these changes

2024-05-08 17:32 UTC, mateus-picoloto submitted a review, later dismissed

2024-05-13 12:54 UTC, mateus-picoloto approved these changes

2024-05-13 13:03 UTC, merged

2024-06-20 19:57 UTC, luiseduardobraschi commented
Posso estar errado, mas aparentemente não estão passando o objeto do pedido ou o ID, então não tem como saber quais são os vendedores envolvidos no pedido.

https://github.com/pagarme/woocommerce/blob/449d27033f17ecf5003cef3e55f439acb02b9899/src/Concrete/WoocommercePlatformOrderDecorator.php#L1217