fix: get recurrence payment in subscription renew
pagarme/woocommerce pull request #500
Opened 2024-10-07 17:06 UTC by RafaMelazzo

![Git Merge](https://media.giphy.com/media/cFkiFMDg3iFoI/giphy.gif)

> [!IMPORTANT]
> Certifique-se de criar o PR para a branch **develop**.

### Qual o tipo de PR é esse? (marque todos os aplicáveis)
- [ ] Refatoração
- [ ] Adição de funcionalidade
- [x] Correção de bug
- [ ] Otimização
- [ ] Atualização de documentação

### Descrição
Adicionado função para busca de pagamento na renovação da assinatura quando a função original falhar

### Cenários testados
Não foi possível replicar erro reportado pelo cliente, portanto efetuei testes mockando a falha e garantindo o recebimento do meta `pagarme_payment_subscription` das opções alternativas.

2024-10-07 17:15 UTC, mauriciohaygert commented on src/Model/Subscription.php
> +    private function formatPaymentMethod($paymentMethod): array
estamos colocando type nas funcitions?

2024-10-07 17:34 UTC, RafaMelazzo commented on src/Model/Subscription.php
> +    private function formatPaymentMethod($paymentMethod): array
Corrigido!

2024-10-10 13:50 UTC, fabiano-mallmann commented on src/Model/Subscription.php
> +            $cardData = $subscription->get_meta('_pagarme_payment_subscription');
Funciona tanto com e sem HPOS?

2024-10-10 13:53 UTC, fabiano-mallmann commented on src/Model/Subscription.php
> +            $cardData = $parentOrder->get_meta('pagarme_payment_subscription');
No de cima, o parâmetro está `_pagarme_payment_subscription` e aqui está somente `pagarme_payment_subscription` , existe alguma razão para isso?
Lembrando que quem realiza a conversão de "com" ou "sem" underscore é a classe Meta, que é extendida por Model/Order, essa tradução não está sendo feita pois está utilizando da classe WC_Order

2024-10-10 13:54 UTC, fabiano-mallmann requested changes

2024-10-10 13:54 UTC, fabiano-mallmann commented on src/Model/Subscription.php
> +        $this->logger = new LogService('Renew Subscription');
Faltou o "use", não?

2024-10-10 17:40 UTC, RafaMelazzo commented on src/Model/Subscription.php
> +     * @return array|false|mixed|string
Foi gerado automaticamente pelo PHPStorm. É um dos possíveis retornos do `get_meta`, e ele deve ter pego da documentação dessa função para completar. Mas no caso do nosso acredito que não tem essa chance. `mixed` também não, apenas `false` ou `string`. Vou remover os dois.

2024-10-11 12:08 UTC, RafaMelazzo commented on src/Model/Subscription.php
> +        $this->logger = new LogService('Renew Subscription');
Não, ele está na linha 24: `use Woocommerce\Pagarme\Service\LogService;`

2024-10-11 21:47 UTC, RafaMelazzo commented on src/Model/Subscription.php
> +            $cardData = $subscription->get_meta('_pagarme_payment_subscription');
Feito alterações para garantir a compatibilidade. Testado com essa opção desabilitada, habilitada e habilitada com modo de compatibilidade ativo.

2024-10-11 21:47 UTC, RafaMelazzo commented on src/Model/Subscription.php
> +            $cardData = $parentOrder->get_meta('pagarme_payment_subscription');
Ajustado!

2024-10-14 17:38 UTC, fabiano-mallmann commented on src/Model/Subscription.php
> +        if (!empty($cardData)) {
Creio que a negativa do empty está incorreta

2024-10-14 18:08 UTC, RafaMelazzo commented on src/Model/Subscription.php
> +        if (!empty($cardData)) {
Ajustado!

2024-10-14 18:44 UTC, mauriciohaygert approved these changes

2024-10-14 21:20 UTC, fabiano-mallmann approved these changes

2024-10-15 13:43 UTC, merged