Feat: Adição do GooglePay no Checkout Blocks
pagarme/woocommerce pull request #501
Opened 2024-10-09 12:45 UTC by fabiano-mallmann

![Git Merge](https://media.giphy.com/media/cFkiFMDg3iFoI/giphy.gif)

> [!IMPORTANT]
> Certifique-se de criar o PR para a branch **develop**.

### Qual o tipo de PR é esse? (marque todos os aplicáveis)
- [ ] Refatoração
- [x] Adição de funcionalidade
- [ ] Correção de bug
- [ ] Otimização
- [ ] Atualização de documentação

### Descrição
Adicionando o Google Pay no Checkoutblocks.

### Cenários testados
Compras no cartão, compras com cartão salvo, compras no Google Pay.

2024-10-09 13:24 UTC, RafaMelazzo requested changes

2024-10-09 13:24 UTC, RafaMelazzo commented on assets/javascripts/front/reactCheckout/payments/CreditCard/useCreditCard.js
> +                    let token = googleCards;
A variável `token` não é alterada. Pode ser definida como `const`

2024-10-09 13:24 UTC, RafaMelazzo commented on assets/stylesheets/front/style.css
> +.pagarme_creditcard_divider p:before {
Acredito que ficaria melhor apenas remover `#payment`. Foi uma definição exagerada inicialmente, rsrs... Se achar necessário, pode alterar o nome da classe para algo mais descritivo, como `pagarme_creditcard_googlepay_checkout_divider` por exemplo.

2024-10-10 13:16 UTC, fabiano-mallmann commented on assets/javascripts/front/reactCheckout/payments/CreditCard/useCreditCard.js
> +                    let token = googleCards;
Removido a variavel

2024-10-10 13:16 UTC, fabiano-mallmann commented on assets/stylesheets/front/style.css
> +.pagarme_creditcard_divider p:before {
Creio que não seja necessário

2024-10-10 16:38 UTC, RafaMelazzo approved these changes

2024-10-14 13:57 UTC, mauriciohaygert approved these changes

2024-10-14 14:01 UTC, merged