Plats 15 improve check card before send order
pagarme/woocommerce pull request #504
Opened 2024-10-21 20:09 UTC by fabiano-mallmann

![Git Merge](https://media.giphy.com/media/cFkiFMDg3iFoI/giphy.gif)

> [!IMPORTANT]
> Certifique-se de criar o PR para a branch **develop**.

### Qual o tipo de PR é esse? (marque todos os aplicáveis)
- [x] Refatoração
- [x] Adição de funcionalidade
- [ ] Correção de bug
- [ ] Otimização
- [ ] Atualização de documentação

### Descrição
Descreva brevemente as alterações feitas neste PR.

### Cenários testados
Descreva brevemente quais foram os cenários testados com as alterações feitas neste PR.

2024-10-21 21:07 UTC, fabiano-mallmann commented
Atende também a tarefa: PLATS-17

2024-10-22 20:03 UTC, RafaMelazzo requested changes

2024-10-25 17:02 UTC, fabiano-mallmann commented on src/Model/Subscription.php
> +    public function asSameCardInSubscription(&$fields, $order)
Alterado

2024-10-25 17:09 UTC, RafaMelazzo approved these changes

2024-10-25 18:10 UTC, mauriciohaygert commented on src/Model/Subscription.php
> +        return false;
Pq volta sempre falso? Tem algum motivo especial?

2024-10-25 18:10 UTC, mauriciohaygert approved these changes

2024-10-25 18:15 UTC, fabiano-mallmann commented on src/Model/Subscription.php
> +        return false;
Tem sim, para poder entrar no fluxo  do **processChangePaymentSubscription** para remover os dados de cartão.

2024-10-28 12:21 UTC, merged